name: shrew_kit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: ^0.18.0
  another_transformer_page_view: ^2.0.1
  go_router: ^8.0.5
  flutter_svg: ^2.0.7
  
  # 유틸리티
  logger: ^2.0.1


  # 예제용으로만 사용
  flutter_week_view: ^1.3.0
  calendar_day_view: ^2.0.0
  calendar_view: ^1.0.3
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/svgs/icons/
